#!/usr/bin/bash

if ! sudo -u workshop --login command -v mvn >/dev/null 2>&1; then
  workshopctl set-health --code="maven-not-on-path" error "Binary 'mvn' not available on the \$PATH."
  exit 0
fi

workshopctl set-health okay
